### ISSUE TITLE
标题右侧的选择框太小

### ISSUE THREAD

**Issue by Chenxiaoxiao** [limingth/crowducate-next#2]
订阅用户胡春波反馈建议：
![image](https://cloud.githubusercontent.com/assets/12248187/7529002/20718b66-f564-11e4-963a-e4d180f3c8d8.png)

**Comment by limingth** [comment]
真正的敏捷开发，快速迭代，让用户有参与感的产品即将要出现了。 大家加油！

## 

李明 / maodou.io

2015-05-08 9:26 GMT+08:00 Chenxiaoxiao notifications@github.com:

**Comment by luckyyang** [comment]
改大了
